image:
  registry: docker.io

ingress:
  className: nginx
  annotations: {}


backend:
  enabled: false

  image:
    repository: h3nryc0ding/accidentally_fancy_footing
    tag: backend

  replicaCount: 1

  ingress:
    hostname: "api.livechat.codehenry.de"

frontend:
  enabled: false

  image:
    repository: h3nryc0ding/accidentally_fancy_footing
    tag: frontend

  replicaCount: 1

  ingress:
    hostname: "livechat.codehenry.de"


mongodb:
  enabled: true
  resourcesPreset: "none"
  nodeSelector:
    kubernetes.io/arch: amd64
  auth:
    postgresPassword: ""
    username: bn_keycloak
    password: ""
    database: livechat
    existingSecret: ""
    secretKeys:
      userPasswordKey: password


  useStatefulSet: true


keycloak:
  enabled: true
  resourcesPreset: "medium"

  auth:
    adminUser: admin
    adminPassword: admin
    existingSecret: ""

  postgresql:
    primary:
      resourcesPreset: "nano"
    nodeSelector:
      kubernetes.io/arch: arm64
