{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livechat
      tier: backend
  template:
    metadata:
      labels:
        app: livechat
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.registry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-backend
              containerPort: 8080
              protocol: TCP
          env:
            - name: BACKEND_URI
              value: "https://{{ .Values.backend.ingress.hostname }}"
            - name: FRONTEND_URI
              value: "https://{{ .Values.frontend.ingress.hostname }}"
            - name: MONGODB_URI
              value: "mongodb://{{ .Values.mongodb.auth.username }}:{{ .Values.mongodb.auth.password }}@{{ .Values.mongodb.service.portName }}:27017/{{ .Values.mongodb.auth.database }}?authSource=admin"
            - name: OAUTH2_ISSUER_URI
              value: "http://{{ .Values.keycloak.ingress.hostname}}/realms/{{ .Values.keycloak.adminRealm }}"
            - name: OAUTH2_CLIENT_ID
            - name: OAUTH2_CLIENT_SECRET
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081
            initialDelaySeconds: 5
{{- end }}
