---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: "weekly"
