{{- if .Values.backend.enabled }}
{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-backend
  annotations: {{- toYaml .Values.backend.ingress.annotations | nindent 4 }}
  labels:
    app: {{ .Chart.Name }}
    component: backend
    tier: backend
spec:
  ingressClassName: nginx
  rules:
    {{- if .Values.backend.ingress.hostname }}
    - host: {{ .Values.backend.ingress.hostname }}
      http:
        paths:
          - path: "/(.*)"
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-backend
                port:
                  number: 3000
    {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.backend.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.backend.ingress.hostname }}
  {{- end }}
{{- end }}
{{- end }}
