{{- if false }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - "{{ .Values.backend.ingress.hostname }}"
        - "{{ .Values.frontend.ingress.hostname }}"
      secretName: tls-secret
  rules:
    - host: "{{ .Values.backend.ingress.hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: "/(.*)"
            backend:
              service:
                name: backend
                port:
                  name: http-backend
    - host: "{{ .Values.frontend.ingress.hostname }}"
      http:
        paths:
          - pathType: Prefix
            path: "/(.*)"
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
{{- end }}
