name: 'Setup pnpm and Node.js'
description: 'Sets up pnpm and Node.js with caching'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
      working-directory: ${{ env.WORKING_DIRECTORY }}
    - name: Install Dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: pnpm install
      shell: bash
