name: 'Setup pnpm and Node.js'
description: 'Sets up pnpm and Node.js with caching'
runs:
  using: "composite"
  steps:
    - run: cd ${{ env.WORKING_DIRECTORY }}
      shell: bash
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm install
      shell: bash
