apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livechat.fullname" . }}
  labels:
    {{- include "livechat.labels" . | nindent 4 }}
data:
  MONGODB_HOST: {{ include "mongodb.service.nameOverride" .Subcharts.mongodb | quote }}
  MONGODB_PORT: {{ .Values.mongodb.service.ports.mongodb | quote }}
  MONGODB_USERNAME: {{ .Values.mongodb.auth.username | quote }}
  MONGODB_DATABASE: {{ .Values.mongodb.auth.database | quote }}
