{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: livechat
      tier: frontend
  template:
    metadata:
      labels:
        app: livechat
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.registry }}/{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-frontend
              containerPort: 3000
              protocol: TCP
          env:
            - name: FRONTEND_URI
              value: "https://{{ .Values.frontend.ingress.hostname }}"
            - name: BACKEND_URI
              value: "https://{{ .Values.backend.ingress.hostname }}"
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 3000
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: "/readyz"
              port: 3000
            initialDelaySeconds: 5
{{- end }}
