{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}
    component: frontend
    tier: frontend
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: {{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: BACKEND_DOMAIN
              value: {{ .Values.backend.ingress.hostname | quote }}
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
{{- end }}
