{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
    component: frontend
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
{{ end }}
