apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.app.image.base }}/backend:{{ .Values.app.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: PUBLIC_FRONTEND_DOMAIN
              value: {{ .Values.ingress.domain }}
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
