apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.app.image.base }}/backend:{{ .Values.app.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: FRONTEND_URL
              value: {{ .Values.ingress.domain }}
            - name: BACKEND_URL
              value: "api.{{ .Values.ingress.domain }}"
            - name: KEYCLOAK_CLIENT_NAME
              value: {{ .Values.keycloak.client.name }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.keycloak.client.id }}
            - name: KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.keycloak.client.secret }}
            - name: KEYCLOAK_ISSUER_URI
              value: "{{ .Values.keycloak.url }}/{{ .Values.keycloak.realm }}"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "4Gi"
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
