apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0-jammy
          ports:
            - containerPort: 27017
          env:
            - name: 'MONGO_INITDB_ROOT_USERNAME'
              value: 'admin'
            - name: 'MONGO_INITDB_ROOT_PASSWORD'
              value: 'root'
            - name: 'MONGO_INITDB_DATABASE'
              value: 'backend_prod'
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP
