spring:
  data:
    mongodb:
      database: dev-database
      username: admin
      password: root
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
PUBLIC_FRONTEND_DOMAIN: localhost:5173