spring:
  data:
    mongodb:
      database: dev-database
      username: admin
      password: root
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

app:
  frontend:
    url: http://localhost:5173
  backend:
    url: http://localhost:8080
