spring:
  data:
    mongodb:
      database: dev-database
      username: admin
      password: root
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://accounts.k8splay.xyz/realms/development
        registration:
          keycloak:
            # credentials are development only
            # feel free to use docker for local development
            client-name: keycloak
            client-id: spring-boot-dev
            client-secret: wWW6jffUZt7BMRyG4LbrHTEgqoxIX6it
            scope: openid
app:
  frontend:
    url: 'http://localhost:5173'
  backend:
    url: 'http://localhost:8080'
