spring:
  data:
    mongodb:
      uri: mongodb://admin:root@mongodb:27017/backend_prod
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 8081
