spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${OAUTH2_ISSUER_URI}
        registration:
          keycloak:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            client-name: livechat
            scope: openid
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  server:
    port: 8081

app:
  frontend:
    url: https://${FRONTEND_DOMAIN}
  backend:
    url: https://${BACKEND_DOMAIN}
