name: 'Setup Playwright'
description: 'Sets up Playwright with caching'
inputs:
  playwright-version:
    description: 'Playwright version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Cache Playwright Browsers
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ inputs.playwright-version }}
    - name: Install Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: pnpm exec playwright install --with-deps
      shell: bash
