name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/actions/docker_build_push.yml
    with:
      directory: ./backend
      image-name: backend
      image-version: latest
      token: ${{ secrets.GITHUB_TOKEN }}
