name: Backend CI

on:
  workflow_call:
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'adopt'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Lint with Ktlint
        run: ./gradlew ktlintCheck

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Assemble with Gradle
        run: ./gradlew assemble

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run tests with Gradle
        run: ./gradlew check
