name: CD Keycloak Deploy

on: workflow_dispatch

defaults:
  run:
    working-directory: .k8s/keycloak

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./.k8s/keycloak
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/keycloak:latest
          cache-from: type=gha,scope=buildkit-keycloak
          cache-to: type=gha,mode=max,scope=buildkit-keycloak

  Deploy:
    needs: [ Build ]
    runs-on: ubuntu-latest
    environment:
      name: accounts
      url: https://accounts.k8splay.xyz
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Kubectl
        uses: Azure/setup-kubectl@v4

      - name: Configure Kubectl
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Deploy Keycloak
        run: |
          kubectl apply -f keycloak.yaml
          kubectl rollout restart deployment/keycloak -n shared
        shell: bash
