name: CI Backend

on:
  push:
  workflow_call:
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'adopt'
  WORKING_DIRECTORY: backend

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Lint with Ktlint
        run: ./gradlew ktlintCheck

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Assemble with Gradle
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-java-gradle
      - name: Run tests with Gradle
        run: ./gradlew check
