name: Cleanup on PR close/merge

on:
  # use target because non-target wouldn't run on conflicts
  pull_request_target:
    types: [ closed ]

permissions:
  contents: read

jobs:
  UninstallApp:
    runs-on: ubuntu-latest
    environment: test
    env:
      NAMESPACE: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Retrieve Source Code
        uses: actions/checkout@v4

      - name: Install Kubectl
        uses: Azure/setup-kubectl@v3

      - name: Configure Kubectl
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Uninstall Helm Chart
        continue-on-error: true
        run: |
          helm uninstall $NAMESPACE -n $NAMESPACE
        shell: bash