name: Fullstack CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-deployment

jobs:
  CreateVersion:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create version tag
        uses: anothrNick/github-tag-action@1.64.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: true
  Dockerize:
    strategy:
      matrix:
        app: [ frontend, backend ]
    needs: [ CreateVersion ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.app }}
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  SaveVersion:
    needs: [ Dockerize ]
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create version tag
        uses: anothrNick/github-tag-action@1.64.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DRY_RUN: false
  Deploy:
    strategy:
      matrix:
        app: [ frontend, backend ]
    needs: [ SaveVersion ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v3

      - name: Setup kubectl
        env:
          K8S_CONFIG: ${{ inputs.k8sconfig }}
        run: |
          mkdir -p $HOME/.kube
          echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Set version for new image
        run: kubectl set image deployment/${{ matrix.app }} ${{ matrix.app }}=ghcr.io/h3nryc0ding/microk8s_plaground/${{ matrix.app }}:${{ needs.SaveVersion.outputs.new_tag }} -n prod
        shell: bash