name: Deployment on PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  CheckFE:
    uses: ./.github/workflows/frontend.yml

  CheckBE:
    uses: ./.github/workflows/backend.yml

  BuildImage:
    if: github.actor != 'dependabot[bot]'
    needs: [ CheckFE, CheckBE ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ frontend, backend ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.app }}
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:$NAMESPACE
          cache-from: type=gha,scope=buildkit-${{ matrix.app }}-pr-$NAMESPACE
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.app }}-pr-$NAMESPACE

  DeployApp:
    needs: [ BuildImage ]
    runs-on: ubuntu-latest
    environment: test
    env:
      NAMESPACE: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: Azure/setup-kubectl@v3

      - name: Configure Kubectl
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Cleanup previous Resources
        run: |
          kubectl delete namespace $NAMESPACE --ignore-not-found
        shell: bash

      - name: Create Namespace and Secrets
        run: |
          kubectl create namespace $NAMESPACE
          
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.repository_owner }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --namespace=$NAMESPACE
          
          echo "${{ secrets.TLS_CERT }}" | base64 --decode > ./tls.crt
          echo "${{ secrets.TLS_KEY }}" | base64 --decode > ./tls.key
          kubectl create secret tls tls-secret \
            --cert=./tls.crt \
            --key=./tls.key \
            --namespace=$NAMESPACE
        shell: bash

      - name: Install App with Helm
        run: |
          helm install $NAMESPACE ./.k8s/app \
          --namespace $NAMESPACE \
          --set ingress.host=$NAMESPACE.k8splay.xyz \
          --set app.image.tag=$NAMESPACE
          --install \
          --wait \
          --atomic \
          --timeout 60s
        shell: bash

      - name: Delete Pull Secret
        run: kubectl delete secret ghcr-secret -n $NAMESPACE
        shell: bash

      - name: Post Deployment Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':rocket: **Your deployment is ready!** :rocket:\n\nYou can access your application at the following link: [https://$NAMESPACE.k8splay.xyz](https://$NAMESPACE.k8splay.xyz)\n\nThis deployment was triggered by pull request #${{ github.event.pull_request.number }}. \n\nRemember, this is a temporary environment for testing purposes. Enjoy exploring your changes in a live setting! :sunglasses:'
            })