name: Deployment on PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  CheckFE:
    uses: ./.github/workflows/frontend.yml

  CheckBE:
    uses: ./.github/workflows/backend.yml

  BuildImage:
    if: github.actor != 'dependabot[bot]'
    needs: [ CheckFE, CheckBE ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ frontend, backend ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.app }}
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.app }}:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha,scope=buildkit-${{ matrix.app }}-pr-${{ github.event.pull_request.number }}
          cache-to: type=gha,mode=max,scope=buildkit-${{ matrix.app }}-pr-${{ github.event.pull_request.number }}

  DeployApp:
    needs: [ BuildImage ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: Azure/setup-kubectl@v3

      - name: Configure Kubectl
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "${K8S_CONFIG}" | base64 --decode > $HOME/.kube/config
        shell: bash

      - name: Cleanup previous Resources
        run: |
          if helm list -n pr-${{ github.event.pull_request.number }} | grep pr-${{ github.event.pull_request.number }}; then
            helm uninstall pr-${{ github.event.pull_request.number }} ./.k8s/app -n pr-${{ github.event.pull_request.number }}
          fi
        shell: bash

      - name: Create Namespace and Docker Secret
        run: |
          if ! (kubectl get namespace pr-${{ github.event.pull_request.number }}); then
          kubectl create namespace pr-${{ github.event.pull_request.number }}
          kubectl create secret docker-registry ghcr-secret \
            --docker-server=ghcr.io \
            --docker-username=${{ github.repository_owner }} \
            --docker-password=${{ secrets.GITHUB_TOKEN }} \
            --namespace=pr-${{ github.event.pull_request.number }}
          fi
        shell: bash

      - name: Install Helm Chart
        timeout-minutes: 60
        run: helm install pr-${{ github.event.pull_request.number }} ./.k8s/app --namespace pr-${{ github.event.pull_request.number }} --set image.tag=pr-${{ github.event.pull_request.number }} --wait
        shell: bash

      - name: Delete Pull Secret
        run: kubectl delete secret ghcr-secret -n pr-${{ github.event.pull_request.number }}
        shell: bash

      - name: Post Deployment Comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':rocket: **Your deployment is ready!** :rocket:\n\nYou can access your application at the following link: [http://pr-${{ github.event.pull_request.number }}.130.61.237.219.nip.io](http://pr-${{ github.event.pull_request.number }}.130.61.237.219.nip.io)\n\nThis deployment was triggered by pull request #${{ github.event.pull_request.number }}. \n\nRemember, this is a temporary environment for testing purposes. Enjoy exploring your changes in a live setting! :sunglasses:'
            })