name: Frontend CI

on:
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: 18
  PNPM_VERSION: 8
  WORKING_DIRECTORY: frontend

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-node
      - name: Run prettier and eslint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-node
      - name: Build Frontend
        run: pnpm build

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm-node
      - uses: ./.github/actions/setup-playwright
      - name: Check Frontend
        run: pnpm check
      - name: Test Frontend
        run: pnpm test
