name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/actions/docker_build_push.yml
    with:
      directory: ./frontend
      image-name: frontend
      image-version: latest
      token: ${{ secrets.GITHUB_TOKEN }}
