name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  Dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and Push Image
        uses: ./.github/actions/docker_build_push
        with:
          directory: ./backend
          image-name: backend
          image-version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
