name: 'Docker Build and Push Composite'
description: 'A composite action for building and pushing Docker images'
inputs:
  directory:
    description: 'The directory to build'
    required: true
  image-name:
    description: 'The name of the image'
    required: true
  image-version:
    description: 'The version of the image'
    required: true
  token:
    description: 'The GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.directory }}
        platforms: linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}:${{ inputs.image-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
